import { pgTable, text, timestamp } from 'drizzle-orm/pg-core'
import { user } from './auth-schema.js'

// Better Auth core + admin + JWT + OAuth 2.1 provider tables (generated by
// `@better-auth/cli generate` into auth-schema.ts).
export * from './auth-schema.js'

// --- Invite-only membership (project-specific, not a Better Auth model) ---

export const invitation = pgTable('invitation', {
  id: text('id').primaryKey(),
  email: text('email').notNull(),
  token: text('token').notNull().unique(),
  role: text('role').default('member').notNull(),
  invitedBy: text('invited_by').references(() => user.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  acceptedAt: timestamp('accepted_at'),
  acceptedBy: text('accepted_by').references(() => user.id, { onDelete: 'set null' })
})
